### ISSUE TITLE
Error with twig-language-server installation

### ISSUE THREAD

**Issue by ralphsun73221** [YussufSassi/zed-twig#5]
Hi,
I encountered an issue while trying to install the twig-language-server. Below are the details of the problem:
Description: I received an error when executing the npm install command for the twig-language-server.

```
Language server error: twig-language-server

failed to execute npm install subcommand:
stdout: ""
stderr: "(node:57774) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().\nSupport for loading ES Module in require() is an experimental feature and might change at any time\n(Use `node --trace-warnings ...` to show where the warning was created)\nnpm error code 1\nnpm error path /Users/sunzhengjie/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig\nnpm error command failed\nnpm error command sh -c node-gyp rebuild\nnpm error gyp info it worked if it ends with ok\nnpm error gyp info using node-gyp@10.2.0\nnpm error gyp info using node@23.1.0 | darwin | arm64\nnpm error gyp info find Python using Python version 3.9.6 found at \"/Library/Developer/CommandLineTools/usr/bin/python3\"\nnpm error (node:57802) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().\nnpm error Support for loading ES Module in require() is an experimental feature and might change at any time\nnpm error (Use `node --trace-warnings ...` to show where the warning was created)\nnpm error gyp http GET https://nodejs.org/download/release/v23.1.0/node-v23.1.0-headers.tar.gz\nnpm error gyp http 200 https://nodejs.org/download/release/v23.1.0/node-v23.1.0-headers.tar.gz\nnpm error gyp http GET https://nodejs.org/download/release/v23.1.0/SHASUMS256.txt\nnpm error gyp http 200 https://nodejs.org/download/release/v23.1.0/SHASUMS256.txt\nnpm error gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3\nnpm error gyp info spawn args [\nnpm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',\nnpm error gyp info spawn args 'binding.gyp',\nnpm error gyp info spawn args '-f',\nnpm error gyp info spawn args 'make',\nnpm error gyp info spawn args '-I',\nnpm error gyp info spawn args '/Users/sunzhengjie/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig/build/config.gypi',\nnpm error gyp info spawn args '-I',\nnpm error gyp info spawn args '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',\nnpm error gyp info spawn args '-I',\nnpm error gyp info spawn args '/Users/sunzhengjie/Library/Caches/node-gyp/23.1.0/include/node/common.gypi',\nnpm error gyp info spawn args '-Dlibrary=shared_library',\nnpm error gyp info spawn args '-Dvisibility=default',\nnpm error gyp info spawn args '-Dnode_root_dir=/Users/sunzhengjie/Library/Caches/node-gyp/23.1.0',\nnpm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',\nnpm error gyp info spawn args '-Dnode_lib_file=/Users/sunzhengjie/Library/Caches/node-gyp/23.1.0/<(target_arch)/node.lib',\nnpm error gyp info spawn args '-Dmodule_root_dir=/Users/sunzhengjie/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig',\nnpm error gyp info spawn args '-Dnode_engine=v8',\nnpm error gyp info spawn args '--depth=.',\nnpm error gyp info spawn args '--no-parallel',\nnpm error gyp info spawn args '--generator-output',\nnpm error gyp info spawn args 'build',\nnpm error gyp info spawn args '-Goutput_dir=.'\nnpm error gyp info spawn args ]\nnpm error gyp: binding.gyp not found (cwd: /Users/sunzhengjie/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig) while trying to load binding.gyp\nnpm error gyp ERR! configure error \nnpm error gyp ERR! stack Error: `gyp` failed with exit code: 1\nnpm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:317:18)\nnpm error gyp ERR! stack at ChildProcess.emit (node:events:507:28)\nnpm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)\nnpm error gyp ERR! System Darwin 24.1.0\nnpm error gyp ERR! command \"/opt/homebrew/Cellar/node/23.1.0_1/bin/node\" \"/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\nnpm error gyp ERR! cwd /Users/sunzhengjie/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig\nnpm error gyp ERR! node -v v23.1.0\nnpm error gyp ERR! node-gyp -v v10.2.0\nnpm error gyp ERR! not ok\nnpm error A complete log of this run can be found in: /Users/sunzhengjie/Library/Application Support/Zed/node/cache/_logs/2024-11-06T23_17_09_951Z-debug-0.log\n"
-- stderr--
```

## Steps to Reproduce:
1. Install Twig in Zed's Extensions.
2. Open any Twig file.

## Environment:
- OS: macOS 15.1
- Node Version: 23.1.0
- npm Version: 10.0.0

Thank you for your help!

**Comment by jannisborgers** [comment]
Hi @ralphsun73221 @YussufSassi I get another error every time I open the first Twig file in a new application session. The status bar shows `Downloading twig-language-server` and after that I get an error like this (I cleaned it up for legibility):

```
2024-11-08T10:22:21.122285+01:00 [ERROR] Failed to start language server "twig-language-server": failed to execute npm install subcommand:
stdout: ""
stderr: "
npm error code 1
npm error path /Users/jannisborgers/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@18.20.4 | darwin | arm64
npm error gyp info find Python using Python version 3.9.6 found at \"/Library/Developer/CommandLineTools/usr/bin/python3\"
npm error gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/opt/homebrew/Cellar/node@18/18.20.4_2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/jannisborgers/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/opt/homebrew/Cellar/node@18/18.20.4_2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/Users/jannisborgers/Library/Caches/node-gyp/18.20.4/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/Users/jannisborgers/Library/Caches/node-gyp/18.20.4',
npm error gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/Cellar/node@18/18.20.4_2/lib/node_modules/npm/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/Users/jannisborgers/Library/Caches/node-gyp/18.20.4/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/Users/jannisborgers/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: binding.gyp not found (cwd: /Users/jannisborgers/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig) while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/Cellar/node@18/18.20.4_2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:297:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:517:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm error gyp ERR! System Darwin 24.0.0
npm error gyp ERR! command \"/opt/homebrew/Cellar/node@18/18.20.4_2/bin/node\" \"/opt/homebrew/Cellar/node@18/18.20.4_2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
npm error gyp ERR! cwd /Users/jannisborgers/Library/Application Support/Zed/extensions/work/twig/node_modules/tree-sitter-twig
npm error gyp ERR! node -v v18.20.4
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok

npm error A complete log of this run can be found in: /Users/jannisborgers/Library/Application Support/Zed/node/cache/_logs/2024-11-08T09_22_20_484Z-debug-0.log
"
2024-11-08T10:22:21.122349+01:00 [ERROR] server stderr: ""
```

When watching the extensions folder, the `work/twig` folder gets a `node_modules` subfolder, but it gets removed immediately. 

Syntax highlighting works without problem.

I'm not sure if this is related, but snippets that I added via `~/.config/zed/snippets/twig.json` don't get triggered. T:

```json
{
  "Set statement": {
    "prefix": "set",
    "body": [
      "{% set ${1} %}",
      "$0"
    ],
    "description": "Set statement"
  },
  "Cache": {
    "prefix": "cache",
    "body": ["{% cache for ${1} using key ${2} %}", "${0}", "{% endcache %}"],
    "description": "Add cache statement"
  }
}
```

**Comment by markvinic** [comment]
I think the problem is with the **npm package tree-sitter-twig**. Here on Ubuntu 22.04.01, it doesn't even install with this node-gyp error:

```bash
$:~/.local/share/zed/extensions/work/twig$ npm i tree-sitter-twig
npm error code 1
npm error path /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig
npm error command failed
npm error command sh -c node-gyp rebuild
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.2.0
npm error gyp info using node@22.11.0 | linux | x64
npm error gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
npm error gyp info spawn /usr/bin/python3
npm error gyp info spawn args [
npm error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/gyp/gyp_main.py',
npm error gyp info spawn args 'binding.gyp',
npm error gyp info spawn args '-f',
npm error gyp info spawn args 'make',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig/build/config.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/addon.gypi',
npm error gyp info spawn args '-I',
npm error gyp info spawn args '/home/vinicius/.cache/node-gyp/22.11.0/include/node/common.gypi',
npm error gyp info spawn args '-Dlibrary=shared_library',
npm error gyp info spawn args '-Dvisibility=default',
npm error gyp info spawn args '-Dnode_root_dir=/home/vinicius/.cache/node-gyp/22.11.0',
npm error gyp info spawn args '-Dnode_gyp_dir=/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp',
npm error gyp info spawn args '-Dnode_lib_file=/home/vinicius/.cache/node-gyp/22.11.0/<(target_arch)/node.lib',
npm error gyp info spawn args '-Dmodule_root_dir=/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig',
npm error gyp info spawn args '-Dnode_engine=v8',
npm error gyp info spawn args '--depth=.',
npm error gyp info spawn args '--no-parallel',
npm error gyp info spawn args '--generator-output',
npm error gyp info spawn args 'build',
npm error gyp info spawn args '-Goutput_dir=.'
npm error gyp info spawn args ]
npm error gyp: binding.gyp not found (cwd: /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig) while trying to load binding.gyp
npm error gyp ERR! configure error 
npm error gyp ERR! stack Error: `gyp` failed with exit code: 1
npm error gyp ERR! stack at ChildProcess.<anonymous> (/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/node-gyp/lib/configure.js:317:18)
npm error gyp ERR! stack at ChildProcess.emit (node:events:518:28)
npm error gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error gyp ERR! System Linux 6.8.0-48-generic
npm error gyp ERR! command "/home/vinicius/.nvm/versions/node/v22.11.0/bin/node" "/home/vinicius/.local/share/zed/extensions/work/twig/node_modules/.bin/node-gyp" "rebuild"
npm error gyp ERR! cwd /home/vinicius/.local/share/zed/extensions/work/twig/node_modules/tree-sitter-twig
npm error gyp ERR! node -v v22.11.0
npm error gyp ERR! node-gyp -v v10.2.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/vinicius/.npm/_logs/2024-11-15T22_41_10_003Z-debug-0.log

```

**Comment by jannisborgers** [comment]
I debugged it and found out that it's not `gbprod/tree-sitter-twig` that fails to install, but the tree-sitter grammar that comes with the bundled LSP `kaermorchen/twig-language-server`. I checked the VSCode extension that the LSP is part of. It also does not work anymore. I think the repo is abandoned.

### Replace LSP and grammar
There is `moetelo/twiggy`, which is a fork of the bundled LSP by kaermorchen, with a lot of additional features. I was able to replace the bundled LSP and the bundled grammar with the twiggy monorepo and could provide a PR.

This is a big change and there are other issues that arise from it, which would have to be handled in the twiggy repo. The syntax highlighting in the Zed extension (`highlights.scm`) needs to be rewritten to capture the syntax nodes that twiggy provides (it is much more complex than `gbprod/tree-sitter-twig`).

**Comment by jannisborgers** [comment]
I got in touch with twiggy’s owner [here](https://github.com/moetelo/twiggy/issues/60) because of some problems I had with including the grammar. He suggested only replacing the language server, not the grammar that Zed uses for it’s own features (highlighting, outline, etc…) and managed to make the extension work again, with code completion etc.: https://github.com/YussufSassi/zed-twig/pull/6

**Comment by guilherme-embroker** [comment]
happy new year! Will the @jannisborgers fix be merged any soon? it would be very useful for me.

**Comment by jannisborgers** [comment]
Hey everyone. 

After the holidays the extension quit working again for me. I think it’s because the twiggy LSP has changed and added some more features, so I rolled back to the last version where Twiggy works for me and [hard-coded the version into the extension](https://github.com/jannisborgers/zed-twig/commit/04070b487c3937cc8bf13885bb40be7723f09234).

Then I fixed a bug where auto-closing resulted in `{{}` and `{%` instead of the intended `{{}}` and `{%%}` by forking gbprod/tree-sitter-twig and [fixing a whitespace problem](https://github.com/gbprod/tree-sitter-twig/pull/19).

I’m hesitant to make a new PR because my current version replaces the grammar with my own temporary grammar repo, I’ll wait until the linked PR is reviewed.

## Try as a dev extension
I’d be happy to get feedback from everyone if this fixes the ongoing issues. You can install my fork as a dev extension (download locally, Click "Add dev extension" in Zed’s extensions window, select local copy and wait a couple of seconds): https://github.com/jannisborgers/zed-twig

**Comment by YussufSassi** [comment]
Fixed by #6
